name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-virt32:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build 
        run: |
          docker run --rm -v "${PWD}:/so3" ghcr.io/smartobjectoriented/so3-env:main bash -c "cd so3 && make virt32_defconfig && make -j`nproc`"

  build-virt64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build
        run: |
          docker run --rm -v "${PWD}:/so3" ghcr.io/smartobjectoriented/so3-env:main bash -c "cd so3 && make virt64_defconfig && make -j`nproc`"

  build-usr:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        CMAKE_TOOLCHAIN_FILE: ['/so3/usr/aarch64_toolchain.cmake', 
                               '/so3/usr/arm_toolchain.cmake']
        BUILD_TYPE: ["Debug", "Release"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build
        run: |
          docker run --rm -t -v "${PWD}:/so3" ghcr.io/smartobjectoriented/so3-env:main bash -c "mkdir usr/build && cd usr/build && cmake --no-warn-unused-cli -DCMAKE_C_FLAGS="-Wall -Werror -Wno-dev" -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE }} -DCMAKE_TOOLCHAIN_FILE=${{matrix.CMAKE_TOOLCHAIN_FILE }} .. && make -j`nproc`"
