name: Docker Image CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # In case we want to build other images we can add them here
        include:
          - dockerfile: ./docker/Dockerfile.env
            image: ghcr.io/smartobjectoriented/so3-env
            submodules: 'false'
          - dockerfile: ./docker/Dockerfile.lvperf_32b
            image: ghcr.io/smartobjectoriented/so3-lvperf32b
            submodules: 'true'
          - dockerfile: ./docker/Dockerfile.lvperf_64b
            image: ghcr.io/smartobjectoriented/so3-lvperf64b
            submodules: 'true'

    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: ${{ matrix.submodules }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
